source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

scriptLint = 'if which ${PODS_ROOT}/SwiftLint/swiftlint > /dev/null; then ${PODS_ROOT}/SwiftLint/swiftlint; else echo "warning: SwiftLint not installed, try pod install"; fi'

target 'EvolvKit_Example' do
	use_frameworks!
	supports_swift_versions '>= 5.0'

	pod 'EvolvKit', :path => '../'
	pod 'SwiftLint'

	script_phase name: 'Lint', script: scriptLint, execution_position: :after_compile

	target 'EvolvKit_Tests' do
		inherit! :search_paths
	end
end
